### ISSUE TITLE
Unhandled Exception: Ghostware.GPS.NET.Exceptions.UnknownTypeException: Unknown Class Type: SKY

### ISSUE THREAD

**Issue by rhysjtevans** [kevingoos/GPS.NET#22]
Hey Kevin,
Great work on this library! 
Hit an issue wonder if you knew anything / could help.

`Unhandled Exception: Ghostware.GPS.NET.Exceptions.UnknownTypeException: Unknown Class Type: SKY
   at Ghostware.GPS.NET.Models.GpsdModels.DataClassType.GetClassType()
   at Ghostware.GPS.NET.Parsers.GpsdDataParser.GetGpsData(String gpsData)
   at Ghostware.GPS.NET.GpsClients.GpsdGpsClient.StartGpsReading(GpsdInfo data)
   at Ghostware.GPS.NET.GpsClients.GpsdGpsClient.Connect()
`

My code looks like -

`var info = new GpsdInfo()
            {
                Address = "192.168.0.32",
                Port = 2947
            };
            _gpsService = new GpsService(info);
            _gpsService.Connect();
            Console.WriteLine(_gpsService.IsRunning);
`

**Comment by rhysjtevans** [comment]
Did some digging it looks like it doesn't like
`{
  "sky":[{"class":"SKY","device":"/dev/ttyUSB0","time":"2012-04-05T15:00:00.000Z","xdop":0.61,"ydop":1.19,"vdop":1.48,"tdop":1.14,"hdop":1.40,"gdop":2.30,"pdop":1.99,"satellites":[{"PRN":26,"el":15,"az":49,"ss":29,"used":true},{"PRN":18,"el":62,"az":315,"ss":31,"used":true},{"PRN":15,"el":60,"az":43,"ss":44,"used":true},{"PRN":21,"el":71,"az":237,"ss":0,"used":false},{"PRN":27,"el":52,"az":94,"ss":40,"used":true},{"PRN":9,"el":48,"az":136,"ss":33,"used":true},{"PRN":22,"el":21,"az":291,"ss":36,"used":true},{"PRN":3,"el":8,"az":303,"ss":25,"used":true}]}]}
`

**Comment by rhysjtevans** [comment]
I created a pr to resolve

**Comment by kevingoos** [comment]
@rhysjtevans I saw your merge request and it looks ok, it is accepted...

I am sorry btw for the late response
I will publisch a new version to nuget on sunday

**Comment by rhysjtevans** [comment]
No Worries @kevingoos, thanks 😄
